<a href="https://colab.research.google.com/github/abustamantes/Mutiple-Linear-Regressor-with-CUDA/blob/main/_ultiple_linear_regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Multiple Linear Regression

## Importing the libraries

In [14]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [15]:
from sklearn.model_selection import train_test_split
dataset = pd.read_csv('x_train.csv')
dataset1 = pd.read_csv('y_train.csv')
dataset2 = pd.read_csv('x_test.csv')
dataset3 = pd.read_csv('y_test_y_pred_should_be_compared_with_this_data.csv')

X_train = dataset.iloc[:, :].values
y_train = dataset1.iloc[:, :].values
X_test=dataset2.iloc[:, :].values
y_test=dataset3.iloc[:, :].values

print(X_train)

[[1617256800       1226        902        324]
 [1617278400       1103        833        270]
 [1617300000       1099        826        273]
 ...
 [1624896000       1165        760        406]
 [1624897800       1104        768        337]
 [1624899600       1155        787        367]]


## Training the Multiple Linear Regression model on the Training set

In [16]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)

LinearRegression()

## Predicting the Test set results

In [17]:
y_pred = regressor.predict(X_test)
print("Values Predicted, this is the values we want to get with CUDA")
print(y_pred)
print("\n")
print("Values Predicted vs real dat")
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

Values Predicted, this is the values we want to get with CUDA
[[14.11]
 [13.36]
 [12.98]
 [13.14]
 [13.31]
 [13.5 ]
 [13.11]
 [12.97]
 [13.86]
 [13.92]
 [13.67]
 [13.43]
 [13.24]
 [13.36]
 [13.01]
 [13.09]
 [12.53]
 [12.18]
 [11.76]
 [11.22]
 [11.01]
 [11.49]
 [11.09]
 [11.12]
 [11.13]
 [10.95]
 [10.8 ]
 [10.76]
 [10.7 ]
 [10.57]
 [10.66]
 [10.69]
 [10.61]
 [10.66]
 [10.51]
 [10.9 ]
 [10.31]
 [10.34]
 [10.54]
 [10.55]
 [10.37]
 [10.32]
 [10.2 ]
 [10.65]
 [10.25]
 [10.25]
 [10.26]
 [10.9 ]
 [11.13]
 [11.2 ]
 [10.74]
 [11.19]
 [11.06]
 [10.76]
 [10.57]
 [10.74]
 [11.04]
 [10.83]
 [10.14]
 [10.33]
 [10.73]
 [10.85]
 [10.39]
 [10.32]
 [10.81]
 [10.84]
 [10.7 ]
 [10.59]
 [10.46]
 [10.42]
 [10.91]
 [10.73]
 [10.43]
 [10.41]
 [10.14]
 [10.76]
 [10.41]
 [10.06]
 [ 9.87]
 [10.32]
 [10.42]
 [10.4 ]
 [10.46]
 [10.22]
 [10.25]
 [10.21]
 [10.51]
 [11.  ]
 [11.57]
 [12.09]
 [13.07]
 [14.53]
 [15.45]
 [15.11]
 [14.97]
 [15.07]
 [14.48]
 [13.79]
 [13.89]
 [13.19]
 [13.01]
 [13.93]
 [14.17]
 [13.56]
 [